# Generated by Django 6.1.1 on 2026-10-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cybrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybrom',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
