# Generated by Django 6.1.1 on 2026-10-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cybrom_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cybrom',
            options={'ordering': ['Name'], 'verbose_name_plural': 'Cybrom'},
        ),
        migrations.AlterField(
            model_name='cybrom',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='cybrom_emp'),
        ),
    ]
