# Generated by Django 6.1.2 on 2026-10-10 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departmentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Studentdepartmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=50)),
                ('depart_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departmentmodel')),
            ],
        ),
    ]
