# Generated by Django 6.1.2 on 2026-10-09 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadharmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Studentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aadhar_no', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.aadharmodel')),
            ],
        ),
    ]
